export { default as Male } from './Male';
export { default as Female } from './Female';
export { default as Femalesecond } from './Femalesecond';
export { default as Femalefirst } from './Femalefirst'
export { default as Femalefourth } from './Femalefourth'
export { default as Jewellery } from './Jewellery'
export { default as Headboard } from './Headboard'
export { default as MaleG } from './MaleG'
export { default as MaleT } from './MaleT'
export { default as Cotton } from './Cotton'
export { default as Cushion } from './Cushion'
export { default as Coat } from './Coat'
export { default as Coa } from './Coa'
export { default as Jew } from './Jew'
export { default as Suit } from './Suit'
